### ISSUE TITLE
You sure "array" works on merge

### ISSUE THREAD

**Issue by kud** [dominictarr/event-stream#84]
I've tried that: https://github.com/dominictarr/event-stream#merge-stream1streamn-or-merge-streamarray

with an array and without an array. Everytime I use the array, it tells me:

```
[15:57:32] TypeError: undefined is not a function
    at /Users/kud/Projects/_playmedia/desktop/node_modules/event-stream/index.js:40:7
    at Array.forEach (native)
    at Object.es.concat.es.merge (/Users/kud/Projects/_playmedia/desktop/node_modules/event-stream/index.js:39:11)
    at Gulp.module.exports (/Users/kud/Projects/_playmedia/desktop/gulp/scripts.js:68:34)
    at module.exports (/Users/kud/Projects/_playmedia/desktop/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/kud/Projects/_playmedia/desktop/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/kud/Projects/_playmedia/desktop/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/kud/Projects/_playmedia/desktop/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/kud/Projects/_playmedia/desktop/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/kud/Projects/_playmedia/desktop/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
```

**Comment by anko** [comment]
There's [a test for that](https://github.com/dominictarr/event-stream/blob/master/test/merge.asynct.js#L26). Could you post a minimal example that causes a failure?

**Comment by kud** [comment]
I've totally changed my code and now it works. Thank you anyway for your help, and thank you for linking me the test. ;)
