### ISSUE TITLE
es.merge. node 5.1.0. Does not work.

### ISSUE THREAD

**Issue by YuraRudkovskiy** [dominictarr/event-stream#91]
Use example at https://www.npmjs.com/package/event-stream

``` sh
es.merge(
  process.stdout,
  process.stderr
).pipe(fs.createWriteStream('output.log'));
```

I have error:

``` sh
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at exports._errnoException (util.js:856:11)
    at WriteStream.Socket._read (net.js:394:21)
    at WriteStream.Readable.read (_stream_readable.js:328:10)
    at WriteStream.Socket.read (net.js:283:43)
    at resume_ (_stream_readable.js:718:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3
```

Could you offer how to fix it?

**Comment by right9ctrl** [comment]
seems not related to this module
